ALTER TABLE pos_goals
ADD COLUMN IF NOT EXISTS target_value NUMERIC DEFAULT NULL,
ADD COLUMN IF NOT EXISTS unit VARCHAR(50) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS description TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS icon VARCHAR(50) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS color VARCHAR(50) DEFAULT NULL;

NOTIFY pgrst, 'reload schema';
