ALTER TABLE cash_closings 
ADD COLUMN IF NOT EXISTS system_cash_total NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_cash_total NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS difference NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS bills_breakdown JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS company_totals JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS manual_sales NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS general_sales_total NUMERIC DEFAULT 0;
